name: Build and deploy server

on:
  push:
    branches: ["main"]
  
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Deploy with rsync
      uses: burnett01/rsync-deployments@7.0.0
      with:
        switches: -avzr --delete
        path: "."
        remote_path: /home/github-deploy/mudlarking-web/
        remote_host: worldenddisk.com
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_KEY }}